### ISSUE TITLE
3.0.1 not working on videos

### ISSUE THREAD

**Issue by Orudeon** [theus/instantgram#22]
Seems to have stopped working on video files as of Jan 9th in Firefox 72.0.1 64bit U.S. region.

I get the error box, "Ops, did you open any Instagram post? Like for example instagram.com/p/82jd828jd." Sometimes it opens a still of the video as a new tab, but not often.

**Comment by shimmyD99** [comment]
getting the same error on carousel pics

**Comment by theus** [comment]
Only with videos? With one video or with a carousel how @shimmyD99 said?

**Comment by Orudeon** [comment]
Currently all videos on the timeline can't be downloaded due to that error. Instagram Stories function fine

**Comment by MaestroDaVinci** [comment]
For me its the opposite. Right now i can download any video, but if the post has multiple images it doesn't work at all.

**Comment by theus** [comment]
I think that Instagram has many versions of their code. Here works as @MaestroDaVinci said.

**Comment by MaestroDaVinci** [comment]
Nice that you are hearing us, but again as i said look my problem as well, if the post has multiple images it doesn't work at all, it says that there isn't any instagram post to get images. I tried it on a post with multiple images and a video and it registered only the video in the post. So there is also a problem with post with multiple images.

**Comment by Orudeon** [comment]
I think theus' point is that it's incredibly difficult to write a one-size-fits-all version of instantgram because instagram's code is not the same in every region or, apparently, even every browser.

**Comment by theus** [comment]
As @Orudeon well said, it's impossible to know all versions because Instagram tests some pieces of features with different users. So, if nobody helps with a pull request, this is what we have.

If you look to the order that [intantgram] works below you'll identify:

https://github.com/theus/instantgram/blob/a0939b00cb1a3e87bf7f71a8bb024b16b16a9028/src/index.js#L72-L83

1. The first type of media that is searched is a video on the page (opened). So, basically, if you open a post with carousel of images and a video (or many) and if `getVideoOnPage` finds a video (in og tag, and I don't know for sure how a video go there _if is the first or don't care to the order_) the program stops the search and bring the video found.
2. If you don't open the post in a new tab, the program will execute `searchVideoOnScreen`. In theory, it will find a video, but, lately, Instagram was testing another version of video referencing, making it impossible the download. [instangram] finds the video but the user can't do download, so, we tell that we don't find (because, in the end, it is not useful).
https://github.com/theus/instantgram/blob/a0939b00cb1a3e87bf7f71a8bb024b16b16a9028/src/modules/searchVideoOnScreen.js#L17-L22 
3. Lastly, `searchImageOnScreen` is executed and search by, as named, images on the screen.

**Comment by dmattera** [comment]
> Instagram was testing another version of video referencing, making it impossible the download.

Yes, the newly added "blob:" references for videos now makes it impossible to pull the src url directly from the HTML element however, the src url is still being sent in the graphql object inside the "__additionalDataLoaded" script which we can access using:

```
(function() {
    var video_url = window.__additionalData[Object.keys(window.__additionalData)[0]]["data"]["graphql"]["shortcode_media"]["video_url"];
    console.log(video_url);
    window.open(video_url);
})();
```

I don't think this exact function will work on videos inside of carousels as we would need to account for the relative index of the video in the carousel when parsing the graphql object but I've confirmed it functions as expected on a page with only a single video:

https://www.instagram.com/p/B7bdzhPC4gX/

**Comment by theus** [comment]
Oh, @dmattera. I didn't know about this `__aditionalData`. 😮 

In fact, in the case of only one video (no carousel) and on his post page we can use this variable. But I noted that if open the post page as modal (only clicking on feed timeline) the `__aditionalData` is empty. This is just populated when entering directly on the post page, like opening in another tab.

🤔

**Comment by rafitamolin** [comment]
Happening here as well. Can't download any Instagram video, no matter whether it's [a standalone video](https://www.instagram.com/p/B7XH6PdlidQ/) or one in a caroussel.

**Comment by theus** [comment]
> Happening here as well. Can't download any Instagram video, no matter whether it's [a standalone video](https://www.instagram.com/p/B7XH6PdlidQ/) or one in a caroussel.

Here the video works fine 😞

**Comment by rafitamolin** [comment]
> > Happening here as well. Can't download any Instagram video, no matter whether it's [a standalone video](https://www.instagram.com/p/B7XH6PdlidQ/) or one in a caroussel.
> 
> Here the video works fine 😞

It seems it fixed itself after a while 🤷🏻‍♂️

**Comment by saschaheim** [comment]
I have made a new repository because of lack of frequently updates here.
https://github.com/ThinkBIG-Company/instantgram
And the new bookmark site:
https://thinkbig-company.github.io/instantgram/

All issues are fixed and multiple videos images in single post are fully supported!
Happy testing issues are welcome

**Comment by theus** [comment]
Hello 👋 (#36)

Can you guys test this version of bookmarklet? It's supposed to resolve the blob issue https://solid-valuable-ox.glitch.me/.

Please, give me feedback. Thanks.
