### ISSUE TITLE
cropped image

### ISSUE THREAD

**Issue by Wag669** [theus/instantgram#34]
Hello!

I would like to report an issue

For the past few hours the bookmarklet gets a cropped version of the picture published in an instagram story.

Example:

If you go to **Brabus** instagram page (_theofficialbrabus_) 
Select the first highlighted story called **COLLECTION 2021** 
And use the borkmarklet on the first story

https://www.instagram.com/stories/highlights/17854622675293273/

you will get this cropped 828x828 version of the pic

https://instagram.fath5-1.fna.fbcdn.net/v/t51.2885-15/e35/c0.322.828.828a/122538454_404644303862981_3873580453993915874_n.jpg?_nc_ht=instagram.fath5-1.fna.fbcdn.net&_nc_cat=105&_nc_ohc=prHhjPONewIAX8bJWw-&tp=1&oh=9b5514211f4546cc06f29425afc2cdec&oe=5FCB6EA8&ig_cache_key=MjQyODQ5NDQ0NDE5MTE2NTc5MQ%3D%3D.2

Instead of this 828x1472 version of the pic 

https://instagram.frix7-1.fna.fbcdn.net/v/t51.2885-15/e35/122538454_404644303862981_3873580453993915874_n.jpg?_nc_ht=instagram.frix7-1.fna.fbcdn.net&_nc_cat=105&_nc_ohc=prHhjPONewIAX8CG9FM&se=8&tp=1&oh=d09ed162796f79059e9d7bbb0bb2341c&oe=5FCBDE6F&ig_cache_key=MjQyODQ5NDQ0NDE5MTE2NTc5MQ%3D%3D.2
 
I tried the 4.0.1 beta version in has the same issue 
 
_Thank you in advance_ 
:)

**Comment by Wag669** [comment]
I think it has to do with pictures in stories going from 1080x1920 to around 1242x2208

**Comment by nationali** [comment]
Yeah, I'm also having this issue. 

It's pretty annoying, though it doesn't happen with every story.

**Comment by Wag669** [comment]
Seems like the problem ...is fixing itself 
For the past few hours I got less and less cropped images

**Comment by Erdloch** [comment]
I have the same issue since weeks / months now, this has never been fixed... The most stories get cropped now, also with the latest version 4.0.3

Example: When you go to https://www.instagram.com/eminem/ and open the first story "MERCH", you see this picture:

![original](https://user-images.githubusercontent.com/49982211/104183225-f0704980-5411-11eb-8f1f-974a4b1e9b2c.jpg)

When I click on the Instantgram bookmark in Firefox 84.0.2, I get a cropped image only:
![Cropped](https://user-images.githubusercontent.com/49982211/104183237-f403d080-5411-11eb-8cc8-008575c76d3e.jpg)
