### ISSUE TITLE
Unable to save Reels

### ISSUE THREAD

**Issue by jeohist** [theus/instantgram#70]
When I attempt to save a reel in 5.0.0, I get the following error in the Developer Tools console:

```
ImageOnScreen() [instantgram] 5.0.0 TypeError: Cannot read properties of undefined (reading 'closest')
    at m (<anonymous>:1:3723)
    at t.execute (<anonymous>:1:5574)
    at Module.<anonymous> (<anonymous>:1:13731)
    at n (<anonymous>:1:123)
    at <anonymous>:1:915
    at <anonymous>:1:924
    at <anonymous>:1:13924
e.error @ VM410:1
t.execute @ VM410:1
(anonymous) @ VM410:1
n @ VM410:1
(anonymous) @ VM410:1
(anonymous) @ VM410:1
(anonymous) @ VM410:1
```

**Comment by jeohist** [comment]
This seems to only happen with reels which do not show up under a user's posts, just under their reels section (no idea how that works, tbh).

**Comment by mklaber** [comment]
Fixed in https://github.com/theus/instantgram-core/pull/2

Meanwhile, if you add a second bookmarklet with this content: `javascript:(function()%7Bwindow.history.pushState(%7B%7D%2C ''%2C location.href.replace('%2Freel%2F'%2C '%2Fp%2F').replace('%2Ftv%2F'%2C '%2Fp%2F'))%7D)()` and click it before clicking `[instantgram]`, it'll make it work.
