### ISSUE TITLE
Can't drag on Mac 

### ISSUE THREAD

**Issue by chnaski** [theus/instantgram#8]
The bookmarklet drag doesn't work on the latest Chrome stable or Canary on Mac. What's the link for a manual install?

**Comment by theus** [comment]
That's weird! I use the latest Chrome on Windows and it's fine. I asked a friend to test on the Mac and it really does not work there. But I found a workaround.

# Workaround

- Step 1
![08_11-15-53](https://user-images.githubusercontent.com/61322/46614209-9de5ab80-caeb-11e8-8210-459af5949d28.gif)
- Step 2: Copy link rather than drag
![image](https://user-images.githubusercontent.com/61322/46614293-db4a3900-caeb-11e8-846f-8cf2b566887c.png)
- Step 3: Edit the bookmark created in step 1
![image](https://user-images.githubusercontent.com/61322/46614347-00d74280-caec-11e8-8a58-21e37d332e64.png)
- Step 4: Paste on URL field
![image](https://user-images.githubusercontent.com/61322/46614426-32500e00-caec-11e8-8dbf-bb2155b73f52.png)

That's all! I hope this workaround works for you =)

**Comment by theus** [comment]
@chnaski please test and tell me if it worked

**Comment by koehntopp** [comment]
Not working for me (Chrome Mac 71.0.3578.98). 
Also, I only found this issue through Google, maybe leave it open or as a hint so others can find it?
Finding the root cause would also be cool ;)

**Comment by ghost** [comment]
Theus's method here is the only way to get it to work on brave Version 0.59.35
