### ISSUE TITLE
Can't extract photos if video is attached

### ISSUE THREAD

**Issue by Orudeon** [theus/instantgram#9]
Similar to issue #6 if a video is attached to a post that has multiple photos, Instantgram seems to prefer grabbing the video. Even more troublesome, if there's more than one video attached, it's inconsistent as to which video it attempts to grab. Later photos in a set seem to be extracted correctly if and only if a video isn't 'near' them.

**Comment by theus** [comment]
Thanks for your issue, @Orudeon.

Seems a complicated situation. Since Instagram change the video source to `blob`, made it difficult to extract video (I think it even isn't possible). So, the solution that I've found was getting the URL of video located in meta tag. In fact, Instantgram prefer to grab this meta tag. But has this situation of many videos in one "album" or videos and photos in one "album".

I'll do some research and tests but this issue is likely to be unresolved 😞

**Comment by theus** [comment]
@Orudeon can you send a link of public post with this behavior?

**Comment by Orudeon** [comment]
This wasn't the one that caused me to notice the issue or the one I was attempting to grab from in the first place, but it exhibits the same behavior. https://www.instagram.com/p/BpXO1KSDgJd/?taken-by=leonchiro

**Comment by theus** [comment]
Thanks, @Orudeon. I actually have a big problem related to updating (more info #10) but I'll look at this issue.

**Comment by Orudeon** [comment]
Oh no, I just read that one. That looks aggravating. Thanks so much for your dedication to this project. Is there some way to tip you for your work?

**Comment by theus** [comment]
I'm glad you like it. When I built this code I was looking to solve a problem that I having. So, I resolved to publish to try to solve other person's problems. 😌

**Comment by saschaheim** [comment]
I have made a new repository because of lack of frequently updates here.
https://github.com/ThinkBIG-Company/instantgram
And the new bookmark site:
https://thinkbig-company.github.io/instantgram/

All issues are fixed and multiple videos images in single post are fully supported!
Happy testing issues are welcome
